version: '3.8'                                                                                                                                                                                                     
services:
  postgres-prod-server:
    container_name: postgres-prod-server-v-9.6.20-alpine
    hostname: postgres-prod-server-v-9.6.20-alpine
    image: postgres:9.6.20-alpine
    environment:
      POSTGRES_PASSWORD: Root123
      PGDATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - /vision/data-storage/docker/postgres-prod-server-v-9.6.20-alpine:/var/lib/postgresql/data
