version: '3.8'                                                                                                                                                                                                     
services:
  mysql-dev-server:
    container_name: mysql-dev-server-v-8.0.23
    hostname: mysql-dev-server-v-8.0.23
    image: mysql:8.0.23
    environment:
      MYSQL_ROOT_PASSWORD: Root123
    ports:
      - 3305:3306
    volumes:
      - /vision/data-storage/docker/mysql-dev-server-v-8.0.23:/var/lib/mysql
      - /vision/conf/docker-conf/mysql-dev-server-v-8.0.23/custom-props.cnf:/etc/mysql/conf.d/custom.cnf
      - /logs/mysql-dev-server-v-8.0.23:/var/log/mysql
